### ISSUE TITLE
when responding to a deal when you are provider, 404

### ISSUE THREAD

**Issue by joshuam10o** [swarmcity/sc-boardwalk#207]
**Actual behavior:** 
When navigating to a deal as a provider, a blank/unresponsive screen is shown. 

**Expected behavior:** 
Deal screen for provider is shown

**Steps to reproduce the problem:**
after being accepted for a request by another party, attempt to open the deal, screen is blank/unresponsive. Appears to be the case for me both in local instance and hosted, but was apparently not experienced by kingflurkel

**Comment by joshuam10o** [comment]
More information, `GET https://philatist-monkey-30658.netlify.com/src/sc-dealfortwoprovider/sc-dealfortwoprovider.html 404 ()` is in console, only happens on desktop devices, uncertain if this is browser-specific

**Comment by sophiii** [comment]
I think this is fixed. Can you confirm and report back ?

**Comment by joshuam10o** [comment]
I'm still getting this error, on all my desktop/chrome/linux devices. I have no idea what's causing it as it doesn't seem to be happening to anyone else.

**Comment by joshuam10o** [comment]
Issue should be in sc-hashtagitem, I'm looking into it

**Comment by sophiii** [comment]
Looks like you are on the right track. Ping me if you need help ;-)

**Comment by joshuam10o** [comment]
Can't figure this out. Would be grateful if anyone helped me debugging. #/dealfortwoprovider/...  is always a 404 on desktop for me. I can't find anything obvious in sc-boardwalk-app or sc-hashtagitem that could be the cause.

**Comment by sophiii** [comment]
i'll take a look.

**Comment by joshuam10o** [comment]
So, one of many commits last night appears to have fixed this issue on one of my machines. I am trying to find who is to blame so I can give them a hug.
I'll confirm and close this when I can access my other machine in the evening today.

**Comment by joshuam10o** [comment]
@kikipluche @sophiii This bug only applies to a specific version of google chrome (55) which is why it only applied to one device I was testing on. Chrome usually autoupdates (I manually updated and can't test the issue anymore), so it should not be an issue in real use. Should we close this issue?

**Comment by sophiii** [comment]
@joshuam10o night mare! Two bugs, one in chrome and one that was fixed with an update. This happens more than you would think. They become particularly difficult to solve. 

Can you close this when you confirm it is solved. :)
